doctrine_migrations:
    migrations_paths:
        'DoctrineMigrations\IdentityAccess': '%kernel.project_dir%/migrations/IdentityAccess'
        'DoctrineMigrations\Shared': '%kernel.project_dir%/migrations/Shared'
        'DoctrineMigrations\Translation': '%kernel.project_dir%/migrations/Translation'
        'DoctrineMigrations\Clinic': '%kernel.project_dir%/migrations/Clinic'
        'DoctrineMigrations\AccessControl': '%kernel.project_dir%/migrations/AccessControl'
        'DoctrineMigrations\Client': '%kernel.project_dir%/migrations/Client'
        'DoctrineMigrations\Animal': '%kernel.project_dir%/migrations/Animal'
        'DoctrineMigrations\Scheduling': '%kernel.project_dir%/migrations/Scheduling'
    enable_profiler: '%kernel.debug%'
    transactional: true
    check_database_platform: true
    storage:
        table_storage:
            table_name: shared__migration_versions
