doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true

        # Custom types for Value Objects
        types: {  }
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: app.orm.naming_strategy.bounded_context_prefix
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: false
        mappings:
            IdentityAccess:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/IdentityAccess/Infrastructure/Persistence/Doctrine/Entity'
                prefix: 'App\IdentityAccess\Infrastructure\Persistence\Doctrine\Entity'
                alias: IdentityAccess
            Translation:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Translation/Infrastructure/Persistence/Doctrine/Entity'
                prefix: 'App\Translation\Infrastructure\Persistence\Doctrine\Entity'
                alias: Translation
            Clinic:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Clinic/Infrastructure/Persistence/Doctrine/Entity'
                prefix: 'App\Clinic\Infrastructure\Persistence\Doctrine\Entity'
                alias: Clinic
            AccessControl:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/AccessControl/Infrastructure/Persistence/Doctrine/Entity'
                prefix: 'App\AccessControl\Infrastructure\Persistence\Doctrine\Entity'
                alias: AccessControl
            Client:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Client/Infrastructure/Persistence/Doctrine'
                prefix: 'App\Client\Infrastructure\Persistence\Doctrine'
                alias: Client
            Animal:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Animal/Infrastructure/Persistence/Doctrine/Entity'
                prefix: 'App\Animal\Infrastructure\Persistence\Doctrine\Entity'
                alias: Animal
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'
            use_savepoints: true

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
