doctrine_migrations:
    migrations_paths:
        'DoctrineMigrations\IdentityAccess': '%kernel.project_dir%/migrations/IdentityAccess'
        'DoctrineMigrations\Shared': '%kernel.project_dir%/migrations/Shared'
        'DoctrineMigrations\Translation': '%kernel.project_dir%/migrations/Translation'
    enable_profiler: '%kernel.debug%'
    transactional: true
    check_database_platform: true
    storage:
        table_storage:
            table_name: shared__migration_versions
