services:
  db:
    image: mysql:8.4.7
    environment:
      - MYSQL_DATABASE=kiveto
      - MYSQL_USER=kiveto
      - MYSQL_PASSWORD=kiveto
      - MYSQL_ROOT_PASSWORD=k!v3t0
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - kiveto-network

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./public:/var/www/html/public:delegated
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php-fpm
    ports:
      - "81:80"
    networks:
      - kiveto-network

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
      args:
        UID: ${HOST_UID:-1000}
        GID: ${HOST_GID:-1000}
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    volumes:
      - ./:/var/www/html:cached
      - ./docker/php-fpm/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    environment:
      - DATABASE_URL=mysql://root:k!v3t0@db/kiveto?serverVersion=8.4.7
    depends_on:
      - db
    networks:
      - kiveto-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    depends_on:
      - db
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=k!v3t0
    ports:
      - "8081:80"
    networks:
      - kiveto-network

volumes:
  mysql_data:
    driver: local

networks:
  kiveto-network:
    driver: bridge
